name: "Redirector App"
app_id: "app-redirector"
customer_id: "yeti"
version: "1.0.0"
description: "Redirector App"

schemas:
  path: schemas/redirect.graphql

resources:
  path: "resources/*.rs"
  root: /api

static:
  path: web
  root: /
  spa: true
  build:
    source: source
    command: npm install && npm run build
